require('dotenv').config();
const Fastify = require('fastify');
const { Pool } = require('pg');
const crypto = require('crypto');

// Helper for Encryption - Updated to GCM for Authenticated Encryption (Integrity Protection)
const ALGORITHM = 'aes-256-gcm';
// We derive a stable 32-byte key from the user's password using a SHA-256 hash
const deriveKey = (password) => crypto.createHash('sha256').update(String(password)).digest('base64').substring(0, 32);

/**
 * Builds and returns a Fastify instance with all routes registered, but does
 * NOT start listening and does NOT touch the database schema. This lets tests
 * (and any other consumer) build the exact same app the server runs, while
 * injecting their own `pool` (e.g. a mocked Pool in unit tests).
 *
 * @param {import('pg').Pool} pool - a pg Pool (or compatible mock) instance
 */
function buildApp(pool) {
    const fastify = Fastify({ logger: false });

    // Enable permissive CORS so the frontend can easily communicate without extra dependencies
    fastify.addHook('onRequest', (request, reply, done) => {
        reply.header('Access-Control-Allow-Origin', '*');
        reply.header('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
        reply.header('Access-Control-Allow-Headers', 'Content-Type');
        if (request.method === 'OPTIONS') {
            reply.send();
        } else {
            done();
        }
    });

    // Route: Get all notes (only metadata, content remains encrypted in DB)
    fastify.get('/api/notes', async (request, reply) => {
        const { rows } = await pool.query('SELECT id, title FROM notes ORDER BY id DESC');
        return rows;
    });

    // Route: Create and encrypt a new note
    fastify.post('/api/notes', async (request, reply) => {
        const { title, content, key } = request.body;

        // Generate an Initialization Vector (IV) for AES
        const iv = crypto.randomBytes(16);
        const encryptionKey = deriveKey(key);

        const cipher = crypto.createCipheriv(ALGORITHM, encryptionKey, iv);
        let encryptedContent = cipher.update(content, 'utf8', 'hex');
        encryptedContent += cipher.final('hex');

        // Extract the authentication tag generated by GCM mode
        const tag = cipher.getAuthTag();

        // Store the encrypted content, IV, and the Auth Tag securely
        const result = await pool.query(
            'INSERT INTO notes (title, encrypted_content, iv, tag) VALUES ($1, $2, $3, $4) RETURNING id, title',
            [title, encryptedContent, iv.toString('hex'), tag.toString('hex')]
        );

        return { success: true, note: result.rows[0] };
    });

    // Route: Decrypt note content
    fastify.post('/api/notes/unlock', async (request, reply) => {
        const { id, key } = request.body;

        const { rows } = await pool.query('SELECT encrypted_content, iv, tag FROM notes WHERE id = $1', [id]);

        if (rows.length === 0) {
            return reply.code(404).send({ error: 'Note not found' });
        }

        try {
            const encryptionKey = deriveKey(key);
            const decipher = crypto.createDecipheriv(ALGORITHM, encryptionKey, Buffer.from(rows[0].iv, 'hex'));

            // GCM requires setting the expected authentication tag before final verification
            decipher.setAuthTag(Buffer.from(rows[0].tag, 'hex'));

            let decrypted = decipher.update(rows[0].encrypted_content, 'hex', 'utf8');
            decrypted += decipher.final('utf8'); // This will throw an error if data or key was tampered with

            return { success: true, content: decrypted };
        } catch (err) {
            return reply.code(403).send({ error: 'Invalid key' });
        }
    });

    return fastify;
}

// Only stand up a real DB connection + listen on a port when this file is
// executed directly (`node index.js`), NOT when it's `require()`'d by tests.
if (require.main === module) {
    const pool = new Pool({
        connectionString: process.env.DATABASE_URL
    });

    const fastify = buildApp(pool);

    const start = async () => {
        try {
            // Updated schema to track the encryption authentication tag column
            await pool.query(`
                CREATE TABLE IF NOT EXISTS notes (
                    id SERIAL PRIMARY KEY,
                    title TEXT NOT NULL,
                    encrypted_content TEXT NOT NULL,
                    iv TEXT NOT NULL,
                    tag TEXT NOT NULL
                );
            `);

            await fastify.listen({ port: 3000, host: '0.0.0.0' });
            console.log(`Server listening on port 3000`);
        } catch (err) {
            fastify.log.error(err);
            process.exit(1);
        }
    };

    start();
}

module.exports = { buildApp, deriveKey, ALGORITHM };