sonar.projectKey=secret-notes-backend
sonar.projectName=Secret Notes Backend
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**
sonar.sourceEncoding=UTF-8