import http from 'k6/http';
import { check, sleep } from 'k6';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:3000';

export const options = {
  scenarios: {
    smoke_and_load: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '20s', target: 10 },
        { duration: '40s', target: 20 },
        { duration: '20s', target: 0 },
      ],
    },
  },
  thresholds: {
    http_req_duration: ['p(95)<800'],
    http_req_failed: ['rate<0.01'],
  },
};

export default function () {
  const listRes = http.get(`${BASE_URL}/api/notes`);
  check(listRes, {
    'GET /api/notes status is 200': (r) => r.status === 200,
    'GET /api/notes returns an array': (r) => Array.isArray(JSON.parse(r.body)),
  });

  const key = `k6-key-${__VU}-${__ITER}`;
  const createPayload = JSON.stringify({
    title: `k6 load note ${__VU}-${__ITER}`,
    content: 'Content generated by k6 load test',
    key,
  });
  const createRes = http.post(`${BASE_URL}/api/notes`, createPayload, {
    headers: { 'Content-Type': 'application/json' },
  });
  const created = check(createRes, {
    'POST /api/notes status is 200': (r) => r.status === 200,
    'POST /api/notes returns success + id': (r) => {
      const body = JSON.parse(r.body);
      return body.success === true && typeof body.note.id === 'number';
    },
  });

  if (created) {
    const noteId = JSON.parse(createRes.body).note.id;

    const unlockRes = http.post(
      `${BASE_URL}/api/notes/unlock`,
      JSON.stringify({ id: noteId, key }),
      { headers: { 'Content-Type': 'application/json' } }
    );
    check(unlockRes, {
      'POST /api/notes/unlock status is 200': (r) => r.status === 200,
      'unlock returns original content': (r) =>
        JSON.parse(r.body).content === 'Content generated by k6 load test',
    });

    const wrongUnlockRes = http.post(
      `${BASE_URL}/api/notes/unlock`,
      JSON.stringify({ id: noteId, key: 'definitely-wrong-key' }),
      {
        headers: { 'Content-Type': 'application/json' },
        responseCallback: http.expectedStatuses(200, 403),
      }
    );
    check(wrongUnlockRes, {
      'wrong key returns 403': (r) => r.status === 403,
    });
  }

  sleep(1);
}